### ISSUE TITLE
Source for german language pack?

### ISSUE THREAD

**Issue by ddorian1** [AnySoftKeyboard/LanguagePack#10]
Is the sourcecode for the German language pack available somewhere?
I found the apk [here](https://code.google.com/p/softkeyboard/downloads/list) and in the Playstore, but can't find the sourcecode. I would love to have it in f-droid, but I think therefor the sourcecode is needed.

**Comment by TimHoepfner** [comment]
Hi @menny! First of all, thank you very much for you brilliant work ... My beer donation is coming :beers:! Like @ddorian1 I am also interested in the source code of the German language pack. Also it would be nice to have the latest language pack at [F-Droid](https://f-droid.org/repository/browse/?fdfilter=anysoft) but more important the latest version of AnySoftKeyboard itself (I know there are some problems because of the build system).

**Comment by menny** [comment]
You can find the sources in the old SVN repo: https://code.google.com/p/softkeyboard/source/browse#svn%2Ftrunk%2FLanguagePacks%2FGerman

**Comment by tuxayo** [comment]
The link is not dead, where are the sources currently hosted ?

I'm trying to find the French pack source that where at some point here: https://softkeyboard.googlecode.com/svn/trunk/LanguagePacks/FrenchXLarge

**Comment by friesenkiwi** [comment]
The old sources archive is currently only available as a SVN dump at
https://code.google.com/archive/p/softkeyboard/source/default/source
But since Google is phasing out its code hosting service, it will probably be removed completely soon.
We are working on resurrecting the "missing" language packs in the other thread (see above) though. It will probably take some weeks.

**Comment by tuxayo** [comment]
> The old sources archive is currently only available as a SVN dump at
https://code.google.com/archive/p/softkeyboard/source/default/source

Oh, all the plugins are in this single repo, I though it was only the main ASK repo. Thanks!

**Comment by friesenkiwi** [comment]
@menny I guess, this can be closed now.

**Comment by menny** [comment]
👍
