### ISSUE TITLE
New Sicilian language pack

### ISSUE THREAD

**Issue by dpaleino** [AnySoftKeyboard/LanguagePack#107]
Hello,
as part of the ongoing effort in making Sicilian (scn) a recognized language by local authorities, I've created, inside [Cadèmia Siciliana](http://www.cademiasiciliana.org) @cademia, a Sicilian keyboard. I therefore ask for the creation of a new branch, so that I can send a PR.

I currently have a nice working keyboard, and have also generated a dictionary. I need to make the latter a bit better, since the given suggestions don't seem of high quality (I'm parsing a dump of scn,wikipedia.org), but I guess this can be improved later.

Thank you for ASK!

**Comment by returntrip** [comment]
Have you managed to create a Sicilian Languagepack? Would love to see Sicilian support. Thanks in advance.

**Comment by dpaleino** [comment]
@returntrip just look for our association on the web, to know more 😉😉😉

**Comment by friesenkiwi** [comment]
Created branch and PR: https://github.com/AnySoftKeyboard/LanguagePack/pull/147 can you resolve the conflicts?

**Comment by MassiminoilTrace** [comment]
Hi, I am creating the language pack for Ligurian.
I ask to you as you succeded to create it in Sicilian.
When I compile and install my ligurian pack on the device, it loads the italian dictionary instead of the ligurian one.
It only works and use the ligurian dictionary if I uninstall the Italian pack. Any ideas?
