### ISSUE TITLE
How long it takes from merged branch to F-Droid relase ?

### ISSUE THREAD

**Issue by azzamsa** [AnySoftKeyboard/LanguagePack#129]

**Comment by friesenkiwi** [comment]
I am sorry that I wasn't able to release earlier to F-Droid, luckily in the meantime somebody took it up in https://github.com/AnySoftKeyboard/LanguagePack/issues/127 and it is released since then: 
https://f-droid.org/packages/com.anysoftkeyboard.languagepack.french/

Generally speaking, because of all the different branches, specialities, things to change and check manually and so on, it is a relatively complex process on our side (check PR, build dev version and run on phone, merge, make sure CircleCI build succeeds (sometimes problems with checkstyle), change icon/store details etc., make littel fixes, tag release on Github, make a MR in fdroiddata repo on Gitlab.com). In the best case, this is a couple of hours, but generally I try to do multiple packs in one batch. In this case, there was a lot of private stuff getting in between merging and releasing.
Afterwards it takes a couple of days until it shows up in the F-Droid Client

**Comment by azzamsa** [comment]
> Luckily in the meantime somebody took it up in #127 and it is released since then.

It's mean she/he did all the process by her/himself. Great.

Reading from your explanation. It seems like very complex process. It's took many process before submitting packages to F-Droid.

Thank you for your contribution.
Thanks for your time for ASK. :)

**Comment by azzamsa** [comment]
Oh no. :(

I did't realize that there are lot of activities happening in [Indonesian branch](https://github.com/AnySoftKeyboard/LanguagePack/commits/Indonesian)

I had some tasks these months. So I never see my LanguagePack fork. I don't know that my commit was behind this branch. I just do updating my F-droid repo to check new ASK release.

Sadly I don't realize that there are many activities happening. And it just handled by two man power

Thank you guys for your time and contribution to community.

**Comment by friesenkiwi** [comment]
Thanks for your words! :-)

About the Indonesian branch: it seems that the latest changes should be mergeable: https://github.com/azzamsa/LanguagePack/compare/Indonesian...AnySoftKeyboard:Indonesian

**Comment by azzamsa** [comment]
> About the Indonesian branch: it seems that the latest changes should be mergeable

Done. :)

**Comment by friesenkiwi** [comment]
Great! And would you like to put up a PR here? I think I might be able to do the merge and release this weekend.

**Comment by azzamsa** [comment]
> Great! And would you like to put up a PR here? I think I might be able to do the merge and release this weekend.

I don't commit any major changes since [this merged](https://github.com/AnySoftKeyboard/LanguagePack/commit/10b3c5b1304cfe68454a356ceb1fef3f00d80d83). I have plan to add more words and statistic. But it's in next version.

**Comment by azzamsa** [comment]
Oh No. :(

I never check Google Play. I always check F-Droid, but never check Google Play. 
I just open it and find Indonesian Language Pack already there.

It's written 'Relased on Feb 28,2018'. 

I opened this issue because every time I checked in F-Droid. I don't find Indonesian language pack in F-dorid. But it turns out it's already in Google play.

Why I don't find it in F-Droid releases ?
