### ISSUE TITLE
Catalan keyboard: Missing characters and wrong order of popups

### ISSUE THREAD

**Issue by David-Gil** [AnySoftKeyboard/LanguagePack#241]
1) In the Catalan keyboard there are some important characters missing: è, é, ú, ü

2) Besides, Catalans usually also write in Spanish and could write in other languages, so other characters are equally important to have: á, ñ, ë, ä, ö.

3) In the top row, popups give numbers as the first option. Numbers are far less used than accentuated vowels and therefore should be left as a secondary option. Grave accents in a, e and o should be first in the popup because they are more common than acute accents in those vowels.

4) The dash symbol should be readily available because it's very common in Catalan.

**Comment by menny** [comment]
merged #242

**Comment by masipcat** [comment]
Hi @David-Gil !

I'm happy to know I'm not the only one interested in the catalan keyboard in ASK :)

I like you your changes except for the fourth point... I expect the letter "P" in the upper-right corner instead of the hyphen ("-"), and this makes me to write a lot of typos...

I propose to create two Catalan keyboards:
- **simplified** as it is without "-"
- **extended** with "-"

What do you think?

**Comment by David-Gil** [comment]
Hi, @masipcat,

In principle, I'm totally ok with your proposal, but before doing something like that, we should think carefully about it because the disposition of the keys makes a huge difference in the speed and precision the user can achieve.

Where would you like the hyphen? It is so common in Catalan that, from my point of view, it should be rapidly accessible.

**Comment by masipcat** [comment]
Hi,

I understand ASK as a free (as in freedom) keyboard replacement for Gboard or Swiftkey. When I use ASK, I expect the "standard Catalan disposition" like in Gboard:

![imatge](https://user-images.githubusercontent.com/775189/54474597-1a8d5c00-47e7-11e9-99f4-0a5a544d8307.png)
*(gboard in catalan)*

![imatge](https://user-images.githubusercontent.com/775189/54474646-9be4ee80-47e7-11e9-8003-c6a431d1ad88.png)
*(ASK catalan keyboard without "-")*

That's why I think that changing the disposition is a downside for all users that are familiarized with the "standard catalan disposition".

You asked me where I would like the hyphen: I want to use the standard disposition so I prefer the hyphen hidden as a subkeyboard in the comma key :P

As I said in the first comment, I think the best solution is to keep a standard keyboard (the one in the picture) and another one with the hyphen (the current one).

I'll open a PR so we can discuss the changes in the code.

**Comment by David-Gil** [comment]
Well, that's the explanation I needed to understand the reasons behind your proposal. Thank you. 

I'm totally ok with your proposal.
