### ISSUE TITLE
French never correct "a" → "à"

### ISSUE THREAD

**Issue by KeooR** [AnySoftKeyboard/LanguagePack#325]
In french when we wrote a "a" alone, most of the time it should be a "à".

For example : 

« Je vais **à** la mer. »
« **À** demain. »

But this keyboard never correct a "a" into a "à" like Gboard does, it's very annoying, I try to add manually "à" as a word in my dictionary but it does nothing. 

Is it possible to add this feature ?

**Comment by menny** [comment]
Are you saying that it should ALWAYS change "a" → "à"? We can do that.
In English, for example, when the user type `i`, it auto-corrects to `I`.

**Comment by S-t-e-p-h** [comment]
Hello,

I've had that problem too. I solved it. Here is the procedure in French (it does not put the "à" by default but proposes it above, just click on it):
Paramètre du clavier AnySoft
Cliquer sur "Langue" (icône globe terrestre)
Choisir "Astuces et plus" /"Réglages avancés" :
Mettre la "longueur minimale de mot pour la correction" à "1"

I have another problem. I have to admit that the French keyboard is not practical (but it is an alternative keyboard!). **It doesn't recognize words with apostrophes that are continually used in French**, especially in conjugated verbs.  I am adding them to my personal dictionary progressively, but it's a long process.  
As a result, I was hoping that the French for AnySoftKeyboard_v4.0.801_apk (2019-12-03) version would be available on F-droid soon because the only version I find there is from 2017.... 

For information: in this short text, in French I have 9 words containing apostrophes ;-)

**Comment by KeooR** [comment]
> Are you saying that it should ALWAYS change "a" → "à"? We can do that.

No, it would be a disaster, "a" mean have at the third-person singular.


> I've had that problem too. I solved it. Here is the procedure in French (it does not put the "à" by default but proposes it above, just click on it):
> Paramètre du clavier AnySoft
> Cliquer sur "Langue" (icône globe terrestre)
> Choisir "Astuces et plus" /"Réglages avancés" :
> Mettre la "longueur minimale de mot pour la correction" à "1"

It worked ! :) Merci beaucoup 👍
