### ISSUE TITLE
Value of f in UserWords.xml and words.xml

### ISSUE THREAD

**Issue by azzamsa** [AnySoftKeyboard/LanguagePack#77]
After following instruction how to create binary dictionary [here](https://code.google.com/archive/p/softkeyboard/wikis/BinaryDictionaries.wiki), which I search and find the app my self trough search engine, cause it is not mentioned in LanguagePack Readme file. :)

I got words.xml with bunch of words, and the value of f=x is up to `f="1586873`, but when we export user dictionary from app the value of f is up to `255`.

1. is it is fine, or we need to tidy up the value of f  manually ? or the app will handle it?
2. I found some non-local Indonesian word in words.xml e.g author,date,time and some strange words e.g ac,a,ad,as,af , do we need to remove it ?, I think removing it in 49789 lines will consume days.

---
during the past days using ASK, I [hack](https://github.com/azzamsa/Ask-Indonesia-UserWords) it to avoid many typos by : 
- renaming words.xml to UserWords.xml 
- put it in `root\sdcard\Android\data\com.menny.android.anysoftkeyboard\files`
- do restore
- finish

but of course non Indonesian suggestion still appears.

---
@menny @friesenkiwi thanks for [#72](https://github.com/AnySoftKeyboard/LanguagePack/pull/72), sorry for late reply, I really waiting you guys, checking that issue almost everyday. but these two week I get some busy in deep village with minimal electricity and internet connection, so sorry for late reply. thanks lot.

**Comment by friesenkiwi** [comment]
Did you have a look at https://github.com/AnySoftKeyboard/LanguagePack/blob/master/build.gradle?
Because usually you don't need to create a binary dictionary file, AnySoftKeyboardTools will generate all dictionaries you need during build from the files you specify in build.gradle. Also, I can't seem to find a binary dictionary in your repo?

The non-local Indonesian words probably come from the https://github.com/azzamsa/ask-indonesian-keyboard/blob/master/dictionary/Indonesian-slang-wikipedia.html
Try cleaning this up and removing all text which is non-Indonesian.

Usually there is no need to touch the generated f= values in the .xml, the app should handle it just fine. But this is just a guess, probably @menny can say more about that.

**Comment by azzamsa** [comment]
@friesenkiwi  thank you so much for you fast and great answer and explanation. thank you so much.

oh, I mean the first time I see pali repo, I think the wordlist is built manually, after some search on how to build such word list, I landed [there](https://code.google.com/archive/p/softkeyboard/wikis/BinaryDictionaries.wiki), and using bash to take word from wikipedia indonesian database to id.xml, this take more than 3 hours in my machine. :)

oh, thanks. 
So I one day I tidy up the word-list, removing non-indonesian word, so I have to creat new PR and the Indonesian Language Pack branch will merge it again ?

thank you so much for your great cotribution to community.

**Comment by friesenkiwi** [comment]
Well thank you for your thanks and praise, but it's actually YOU who contribute to the community, I just try to help with that as far as I can. So thank you! :)

Probably the best would be to actually fork the LanguagePack repo, because otherwise the PR functionality of Github unfortunately doesn't work :-(

You can try to build the master branch or another language for example Hebrew or German to see how everything in the build works together and which files are automatically generated by the AnySoftKeyboardTools. You CAN use binary dictionaries (I wouldn't know how to get all the Wikipedia data into ASK any other way), but you need to include them in the repository (and in build.gradle), otherwise the F-Droid build won't work.
If you leave it like now, it will result in a dictionary containing only Indonesian-slang-wikipedia.html and popular_websites_words.xml. The pali repo is pretty old and as such doesn't use the methods developed for the newer language packs.

**Comment by friesenkiwi** [comment]
Closing this in favor of #78
